[package]
name = "bot7685-ext"
version = "0.1.2"
edition = "2024"
repository = "https://github.com/wyf7685/Bot7685-ext"

[dependencies]
image = "0.25.8"
lazy_static = "1.5.0"
pyo3 = { version = "0.27.1", features = ["abi3", "extension-module"] }

[lib]
name = "_ext"
crate-type = ["cdylib", "rlib"]
