[project]
name = "bot7685-ext"
description = "Extensions for Bot7685"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
dynamic = ["version"]

[project.optional-dependencies]
nonebot = ["nonebot2>=2.4.4"]
htmlrender = [
    "bot7685-ext[nonebot]",
    "httpx[http2]>=0.27.0",
    "nonebot-plugin-htmlrender>=0.6.7",
]

[build-system]
requires = ["maturin>=1.9.6,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = ["maturin>=1.9.6,<2.0"]

[tool.maturin]
manifest-path = "Cargo.toml"
python-source = "python"
module-name = "bot7685_ext._ext"
bindings = "pyo3"

[tool.uv]
package = true

[tool.uv.sources]
bot7685-ext = { workspace = true }
